### ISSUE TITLE
Modificar el convert.py para poder nosotros seleccionar el audio de entrada y el target speaker para generar un nuevo audio.

### ISSUE THREAD

**Issue by josearangos** [Integrador-VoiceStyleTransfer/Voice-Conversion#4]
- [x] All vs All

- [x] One vs One

- [x] All vs One

- [x] One vs All

**Comment by cdanmontoya** [comment]
Done. Please review the [pull request](https://github.com/Integrador-VoiceStyleTransfer/multitarget-voice-conversion-vctk/pull/1).
